### ISSUE TITLE
SMS password does not come

### ISSUE THREAD

**Issue by mor1ins** [vyachkonovalov/plugin.video.movix#1]
Hello!

I'm trying to use your addon, but SMS password does not come. 
I am using LibreELEC version 9.2.2 (kodi 18.6, running in a virtual machine). Plugin installed via zip archive. There is Internet on VM. Any ideas?
Thanks for your hard work!

**Comment by vyachkonovalov** [comment]
Hi. I didn't notice there is login by phone number + sms. You could use your [contract number | email | phone] + password by now.
> Thanks for your hard work!

Your welcome. It wasn't hard though😁

**Comment by mor1ins** [comment]
Yes, domra has this option by default. And I mixed up the two login methods.

**Comment by vyachkonovalov** [comment]
Not rolling new release for this update. Here's new version [plugin.video.movix-0.2.0.zip](https://github.com/vyachkonovalov/plugin.video.movix/files/4540680/plugin.video.movix-0.2.0.zip)
If you'd like to test it (Sign in by SMS), please [sign out](https://github.com/vyachkonovalov/plugin.video.movix#sign-out) first.
